version: "3.4"
services:
  reverse_proxy:
    image: nginx:latest
    container_name: "reverse_proxy"
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"
